name: Build

on: [push, pull_request]

jobs:
  build:
    name: ACTS (Windows)
    runs-on: windows-latest
    strategy:
      matrix:
        cfg:
          - Release
          - Debug
        platform:
          - x64
    steps:
      - uses: actions/checkout@v3.5.3
      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.3.1
      - name: Setup premake5
        uses: abel0b/setup-premake@v2.3
        with:
          version: "5.0.0-beta2"
      - name: Create project
        run: premake5 vs2022
      - name: Build project
        run: |
          msbuild build/AtianCodTools.sln /p:Configuration=${{matrix.cfg}} /p:Platform=${{matrix.platform}}
      - name: Upload files
        uses: actions/upload-artifact@v1
        if: matrix.cfg == 'Release'
        with:
          name: "Windows"
          path: "build/bin/acts.exe"

